{% set version = "3.7.1" %}

package:
  name: flake8
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/flake8/flake8-{{ version }}.tar.gz
  sha256: e9ca1bb84d76511315e565a2cdd292d916b08b0d639aa3e323d8c7d895a03897

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
    - pytest-runner
  run:
    - configparser  # [py2k]
    - enum34  # [py2k or py33]
    - mccabe >=0.6.0,<0.7.0
    - pycodestyle >=2.4.0,<2.5.0
    - pyflakes >=2.0.0,<2.1.0
    - python
    - setuptools >=30.0.0
test:
  imports:
    - flake8
  source_files:
    - src/flake8
    - tests/integration
    - tests/unit
    - setup.py

  commands:
    - flake8 --ignore=D203,W503,E203 src/flake8 tests/integration tests/unit setup.py  # [unix]
    - flake8 --ignore=D203,W503,E203 src\\flake8 tests\\integration tests\\unit setup.py  # [win]

about:
  home: http://flake8.pycqa.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Your Tool For Style Guide Enforcement'
  doc_url: http://flake8.pycqa.org/
  dev_url: https://gitlab.com/pycqa/flake8

extra:
  recipe-maintainers:
    - sigmavirus24
    - croth1
    - dopplershift
    - goanpeca
    - aydinhan
