{%set name = "flake8" %}
{%set version = "3.0.3" %}
{%set hash_type = "sha256" %}
{%set hash_val = "fa8ebbdc9a78991af150b86cd0e3377361586ce7d1fed0079f0077f2ada227ec" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner

  run:
    - python
    - setuptools
    - mccabe
    - pycodestyle
    - pyflakes

test:
  imports:
    - {{ name }}

about:
  home: http://flake8.pycqa.org/
  license: MIT
  summary: 'Your Tool For Style Guide Enforcement'

extra:
  recipe-maintainers:
    - sigmavirus24
